---
- name: Restart velociraptor-server
  ansible.builtin.systemd:
    name: velociraptor
    state: restarted
    daemon_reload: true
    enabled: true
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: URL
  ansible.builtin.debug:
    msg: "You can reach Velociraptor via https://{{ ansible_default_ipv4.address }}:8889/"

- name: Restart velociraptor nix client
  ansible.builtin.systemd:
    name: velociraptor-client
    state: restarted
    daemon_reload: true
    enabled: true
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: Restart velociraptor windows client
  ansible.windows.win_service:
    name: Velociraptor
    state: restarted
