---

- name: Verify
  hosts: dinosaurs
  tasks:
    - name: Check client systemd is present
      ansible.builtin.stat:
        path: /lib/systemd/system/velociraptor-client.service
      register: systemd
    - name: Validate systemd service file is present
      ansible.builtin.assert:
        that: systemd.stat.exists

    - name: Run velociraptor version
      ansible.builtin.command: /opt/velociraptor/velociraptor version
      changed_when: false
      register: v
    - name: Validate run
      ansible.builtin.assert:
        that: "'name: velociraptor' in v.stdout"
